config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :admin, only: [:index]
  resources :clients
  resources :projects do
    resources :tickets
    resources :dashboard, only: [:index]
    resources :chat, only: [:index, :create]
    resources :reports, only: [:index, :show, :new, :create, :destroy]
  end
  resources :employees

  resources :tickets, only: [:show] do
    resources :comments
  end

  get 'projects/:id/developers' => 'projects#developers', as: :project_developers
  get 'projects/:id/testers' => 'projects#testers', as: :project_testers
  post '/projects/:id/developers' => 'projects#manage_developers'
  post '/projects/:id/testers' => 'projects#manage_testers'

  #not sure this is the right way to do it
  #voiam doar ca o actiune din controller sa se execute in momentul in care se apasa pe un buton
  put '/projects/:project_id/dashboard/change_status/:ticket_id' => 'dashboard#change_status', as: :change_status

  #for downloading file in a ticket
  get '/projects/:id/dashboard/:attachment' => 'dashboard#download', :constraints => {:attachment => /.*/ }, as: :download_file

  #for subtasks
  get '/projects/:project_id/tickets/new/(:owner)' => 'tickets#new', as: :new_project_subticket

  #deleting attachments
  delete 'projects/:id/attachment/:attachment_id' => 'projects#delete_attachment', as: :project_delete_attachment
  delete 'tickets/:id/attachment/:attachment_id' => 'tickets#delete_attachment', as: :ticket_delete_attachment
  delete 'tickets/:ticket_id/comments/:id/attachment/:attachment_id' => 'comments#delete_attachment', as: :comment_delete_attachment

  #tickets details
  get '/projects/:project_id/tickets/:id/time_tracking' => 'tickets#time_tracking', as: :ticket_time_tracking
  get '/projects/:project_id/tickets/:id/attachments' => 'tickets#attachments', as: :ticket_attachments

  #cum pot sa accesez o actiune din controller fara sa creez o intreaga ruta pt asta?
  #am incercat cu <%= link_to "", controller: "comments", action: "decrease_step" do %> dar nu a mers
  put 'tickets/:ticket_id/decrease_step' => 'comments#decrease_step', as: :decrease_step
  put 'tickets/:ticket_id/increase_step' => 'comments#increase_step', as: :increase_step

  #for reports
  post '/projects/:project_id/reports/tickets_priority' => 'reports#tickets_priority'
  post '/projects/:project_id/reports/refill_employees_dropdown' => 'reports#refill_employees_dropdown'

  #for realtime chat
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < User
  has_many :roles
  has_many :projects, :through => :roles
  has_many :tickets

  def is_projectmanager?(project)
    get_role(project).role == "projectmanager"
  end

  def is_developer?(project)
    unless get_role(project).nil? #can be nil actually, see developers, at checkbox
      get_role(project).role == "developer"
    end
  end

  def is_tester?(project)
    unless get_role(project).nil? #can be nil actually, see testers, at checkbox
      get_role(project).role == "tester"
    end
  end

  def get_projectmanager_role_projects
    projects = []

    roles.where(role: 'projectmanager').each do |role|
      projects.push(Project.find(role.project_id))
    end

    projects
  end

#ticket --------------------------------------------------------------------------
  def can_add_ticket?(project)
    is_projectmanager?(project)
  end

  def can_add_subticket?(ticket)
    (ticket.employee_id == id) && (ticket.status != "Complete") && (ticket.status != "Done")
  end

  def can_modify_ticket?(project, ticket)
    (ticket.status != "Done") && (is_projectmanager?(project) || (ticket.owner && ticket.owner == id))
  end

  def can_add_bug?(project, task)
    (is_tester?(project)) && (task.status == "Complete") && (task.type != "Bug")
  end

  def can_send_ticket_back?(project, ticket)
    (is_developer?(project) && has_ticket?(ticket) && (ticket.status == "In progress" || ticket.status == "Complete")) || (is_tester?(project) && (ticket.status == "Complete" || ticket.status == "Done"))
  end

  def can_send_ticket_forward?(project, ticket)
    (is_developer?(project) && has_ticket?(ticket) && (ticket.status == "To do" || ticket.status == "In progress")) || (is_tester?(project) && ticket.status == "Complete")
  end

  def has_ticket?(ticket)
    ticket.employee_id == id
  end

  def can_modify_comment?(comment)
    id == comment.user_id
  end

#chat --------------------------------------------------------------------------
  def can_see_chat?(project)
    is_projectmanager?(project)
  end

  def can_chat?(project)
    is_projectmanager?(project)
  end

#reports -----------------------------------------------------------------------
  def can_see_reports?(project)
    is_projectmanager?(project)
  end

  def get_nr_of_tickets(conditions)
    tickets.where(conditions).count
  end

  def self.get_selected_employees_for_columnchart(container, employees_ids)
    employees_ids.each do |employee_id|
      container.push(Employee.find(employee_id))
    end
  end

#others ------------------------------------------------------------------------
  def self.get_employees_filtered_by_role(employee_id)
    projects_projectmanager_role, projects_developer_role, projects_tester_role = [], [], []

    Employee.find(employee_id).roles.each do |role|
      case role.role
      when "projectmanager"
        projects_projectmanager_role.push(role.project)
      when "developer"
        projects_developer_role.push(role.project)
      when "tester"
        projects_tester_role.push(role.project)
      end
    end

    return projects_projectmanager_role, projects_developer_role, projects_tester_role
  end

  def get_role(project)
    Role.find_by(project_id: project.id, employee_id: id)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee_by_id, only: [:show, :edit, :update, :destroy]
  before_action :get_employees, only: [:index, :show, :new, :create, :edit, :update]

  def index
  end

  def show
    @roles = @employee.roles
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employee_path(@employee)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to employee_path(@employee)
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path
  end

  private
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :username, :password, :email, :function, :file)
  end

  def find_employee_by_id
    @employee = Employee.find(params[:id])
  end

  def get_employees
    @employees = Employee.all
  end
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, local: true, class: 'form-horizontal' do |form| %>

  <% if @employee.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:
    </h2>
    <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="container-fluid">
    <div class="form-group required">
      <%= form.label :first_name, class: 'control-label col-sm-1'%>
      <div class="col-sm-4">
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group required">
      <%= form.label :last_name, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group required">
      <%= form.label :username, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.text_field :username, class: 'form-control' %>
        <small class='form-text text-muted'>Must contain at least 3 letters</small>
      </div>
    </div>

    <div class="form-group required">
      <%= form.label :password, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.text_field :password, class: 'form-control' %>
        <small class='form-text text-muted'>Must contain at least 6 letters</small>
      </div>
    </div>

    <div class="form-group required">
      <%= form.label :email, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.text_field :email, class: 'form-control', placeholder: 'example@email.com' %>
        <small class='form-text text-muted'>Must have lowercase letters</small>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :function, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.text_field :function, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :profile_picture, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.file_field :file, class: 'form-control-file' %>
      </div>
    </div>

    <br>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-1">
        <%= form.submit "Save" %>
      </div>
      <%= link_to '<button type="button">Cancel</button>'.html_safe, employees_path, style: 'color: black;' %>
    </div>

    <br>
    <p><span style="color:red">* </span>fields are mandatory</p>

  </div>
<% end %>

app/views/employees/_left_sidebar.html.erb
<div class="sidenav">
  <% if current_user.can_see_employees? %>
    <% @employees.each do |employee| %>
      <%= link_to employee.full_name, employee_path(employee) %></a>
    <% end %>
  <% end %>

  <% if current_user.can_modify_employee? %>
    <div class="footer">
      <%= link_to 'Add new employee', new_employee_path %>
    </div>
  <% end %>
</div>

app/views/employees/details_project.html.erb
<%= form_with local: true do |form| %>
  <p>
    <h1><b>Project:</b> <%= form.label @project.title %></h1>
  </p>

  <p>
    <b>Description: </b><%= form.label @project.description %>
  </p>

  <p>
    <b>Developers</b><br>
    <% @project_developers_roles.each do |role| %>
      <%= role.employee.full_name %><br>
    <% end %>
  </p>

  <p>
    <b>Testers</b><br>
    <% @project_testers_roles.each do |role| %>
      <%= role.employee.full_name %><br>
    <% end %>
  </p>

<% end %>

<%= form_with :url => add_new_project_employees_path, local: true do |form| %>
  <p><b>Add more developers</b></p>
  <%= form.fields_for :developers do |builder| %>
    <%= builder.collection_select(:id, @available_employees, :id, :full_name,
                                  { include_hidden: false },
                                  { :multiple => true }) %>
    <% end %><br>
  <%= form.submit("Add") %>
<% end %>

<%= form_with :url => add_new_project_employees_path, local: true do |form| %>
  <p><b>Add more testers</b></p>
  <%= form.fields_for :testers do |builder| %>
    <%= builder.collection_select(:id, @available_employees, :id, :full_name,
                                  { include_hidden: false },
                                  { :multiple => true }) %>
    <% end %><br>
  <%= form.submit("Add") %>
<% end %>

<p>
  <%= link_to "New task", new_task_path(@project) %>
</p>

app/views/employees/edit.html.erb
<%= render 'left_sidebar' %>

<div class="main">
  <h1>Edit employee</h1>
  <%= render 'form' %>
</div>

app/views/employees/index.html.erb
<%= render 'left_sidebar' %>

app/views/employees/new.html.erb
<%= render 'left_sidebar' %>

<div class="main">
  <h1>Fill in form to add a new employee</h1>
  <%= render 'form' %>
</div>

app/views/employees/show.html.erb
<%= render 'left_sidebar' %>

<div class="main">
    <div class="container-fluid">
      <div class="row">
        <% unless @employee.file_url.nil? %>
          <div class="col-md-2 col-lg-2" align="center"><%= image_tag @employee.file_url, :size => "200x200", class: "img-circle img-responsive"%> </div>
        <% end %>

        <div class="col-md-9  col-lg-9">
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td><b>Name:</b></td>
                <td><%= @employee.full_name %></td>
              </tr>
              <tr>
                <td><b>Username:</b></td>
                <td><%= @employee.username %></td>
              </tr>
              <tr>
                <td><b>Function:</b></td>
                <td><%= @employee.function %></td>
              </tr>
              <tr>
                <td><b>Email:</b></td>
                <td><%= @employee.email %></td>
              </tr>
              <tr>
                <td><b>Roles:</b></td>
                <td>
                  <% @roles.each do |role| %>
                    <%= role.project.title %> -> <%= role.role %><br>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>

          <% if current_user.can_modify_employee? %>
            <%= link_to edit_employee_path(@employee), class: "btn btn-warning", title: 'Edit employee' do %>
              <i class="glyphicon glyphicon-edit"></i>
            <% end %>

            <%= link_to employee_path(@employee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", title: 'Delete employee' do %>
              <i class="glyphicon glyphicon-remove"></i>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>
</div>