config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :admin, only: [:index]
  resources :clients
  resources :projects do
    resources :tickets
    resources :dashboard, only: [:index]
    resources :chat, only: [:index, :create]
    resources :reports, only: [:index, :show, :new, :create, :destroy]
  end
  resources :employees

  resources :tickets, only: [:show] do
    resources :comments
  end

  get 'projects/:id/developers' => 'projects#developers', as: :project_developers
  get 'projects/:id/testers' => 'projects#testers', as: :project_testers
  post '/projects/:id/developers' => 'projects#manage_developers'
  post '/projects/:id/testers' => 'projects#manage_testers'

  #not sure this is the right way to do it
  #voiam doar ca o actiune din controller sa se execute in momentul in care se apasa pe un buton
  put '/projects/:project_id/dashboard/change_status/:ticket_id' => 'dashboard#change_status', as: :change_status

  #for downloading file in a ticket
  get '/projects/:id/dashboard/:attachment' => 'dashboard#download', :constraints => {:attachment => /.*/ }, as: :download_file

  #for subtasks
  get '/projects/:project_id/tickets/new/(:owner)' => 'tickets#new', as: :new_project_subticket

  #deleting attachments
  delete 'projects/:id/attachment/:attachment_id' => 'projects#delete_attachment', as: :project_delete_attachment
  delete 'tickets/:id/attachment/:attachment_id' => 'tickets#delete_attachment', as: :ticket_delete_attachment
  delete 'tickets/:ticket_id/comments/:id/attachment/:attachment_id' => 'comments#delete_attachment', as: :comment_delete_attachment

  #tickets details
  get '/projects/:project_id/tickets/:id/time_tracking' => 'tickets#time_tracking', as: :ticket_time_tracking
  get '/projects/:project_id/tickets/:id/attachments' => 'tickets#attachments', as: :ticket_attachments

  #cum pot sa accesez o actiune din controller fara sa creez o intreaga ruta pt asta?
  #am incercat cu <%= link_to "", controller: "comments", action: "decrease_step" do %> dar nu a mers
  put 'tickets/:ticket_id/decrease_step' => 'comments#decrease_step', as: :decrease_step
  put 'tickets/:ticket_id/increase_step' => 'comments#increase_step', as: :increase_step

  #for reports
  post '/projects/:project_id/reports/tickets_priority' => 'reports#tickets_priority'
  post '/projects/:project_id/reports/refill_employees_dropdown' => 'reports#refill_employees_dropdown'

  #for realtime chat
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :clients, join_table: :clients_projects
  has_many :roles, dependent: :destroy
  has_many :employees, :through => :roles
  has_many :tickets, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :reports, dependent: :destroy

  has_many :attachments, as: :container, dependent: :destroy

  validates :title, presence: true

  def get_projectmanager
     roles.where(:role => "projectmanager").take.employee
  end

  def get_developers
    developers =  []

    roles.where(:role => "developer").each do |role|
      developers.push(role.employee)
    end

    developers
  end

  def get_testers
    testers = []

    roles.where(:role => "tester").each do |role|
      testers.push(role.employee)
    end

    testers
  end

#reports -----------------------------------------------------------------------
  def get_employee_hash_for_piechart
    hash = tickets.group(:employee_id).count
    hash.transform_keys { |key| Employee.find(key).full_name } #to replace employee_id with the employee's name
  end

  def self.get_employees_from_selected_projects_for_columnchart(container, projects_ids)
    projects_ids.each do |project_id|
      Project.find(project_id).employees.each do |employee|
        unless container.include?(employee)   # to eliminate duplicates
          container.push(employee)
        end
      end
      #@employees_for_columnchart.push(Project.find(project_id).employees) - couldn't do this because Project.find(project_id).employees returns a CollectionProxy object
      #                                                                      which doesn't allow me to acces full_name method on its array objects
    end
  end

  def self.nr_of_unsolved_tickets(project_list)
    unsolved_tickets = 0

    project_list.each do |project_id|
      unsolved_tickets += Project.find(project_id).tickets.where(status: ["To do", "In progress", "Complete"]).count
    end

    unsolved_tickets
  end

  def self.nr_of_urgent_tickets(project_list)
    pending_tickets = 0

    project_list.each do |project_id|
      Project.find(project_id).tickets.each do |ticket|
        if (Time.now..Time.now + 7.days).include?(ticket.deadline)
          pending_tickets += 1
        end
      end
    end

    pending_tickets
  end

  def tickets_bugs_report
    nr_of_tickets = tickets.where(type: 1).count
    nr_of_bugs    = tickets.where(type: 2).count

    if nr_of_bugs != 0
      (nr_of_tickets / nr_of_bugs.to_f).round(2)
    else
      "no bugs"
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project_by_id, only: [:show, :edit, :update, :destroy, :developers, :testers, :manage_developers, :manage_testers]

  #for project manager dropdown
  before_action :get_employees, only: [:new, :create, :edit, :update, :developers, :testers]

  #for clients check boxes
  before_action :get_clients, only: [:new, :create, :edit, :update]

  #index and show are common for admin and employee
  before_action :setup_left_sidebar, only: [:index, :show, :new, :create, :edit, :update, :developers, :testers]


  def index
  end

  def show
    @projectmanager = @project.get_projectmanager
    @developers = @project.get_developers
    @testers = @project.get_testers
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      add_files
      add_projectmanager_role
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def edit
    #to have a selected employee on dropdown
    @projectmanager = @project.get_projectmanager
  end

  def update
    if @project.update(project_params)
      add_files
      update_projectmanager_role
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def delete_attachment
    attachment = Attachment.find(params[:attachment_id])
    attachment.destroy
    redirect_to edit_project_path(Project.find(attachment.container_id))
  end

  def developers
    #refactor
    @available_employees = Employee.all - @project.get_testers.push(@project.get_projectmanager)
  end

  def testers
    #refactor
    @available_employees = Employee.all - @project.get_developers - [@project.get_projectmanager]
  end

  def manage_developers
    destroy_existing_developers

    #can be better?
    unless params[:developer_ids].nil?
      params[:developer_ids].each do |developer_id|
        @role = Role.new(developer_role_params(developer_id))
        @role.save
      end
    end

    redirect_to project_path(@project)
  end

  def manage_testers
    destroy_existing_testers

    #can be better?
    unless params[:tester_ids].nil?
      params[:tester_ids].each do |tester_id|
        @role = Role.new(tester_role_params(tester_id))
        @role.save
      end
    end

    redirect_to project_path(@project)
  end

#-------------------------------------------------------------------------------
  private
  def project_params
    params.require(:project).permit(:title, :description, client_ids:[])
  end

  def permit_files
    params.require(:project).permit({files: []})
  end

  def find_project_by_id
    @project = Project.find(params[:id])
  end

  def get_employees
    @employees = Employee.all
  end

  def get_projects
    @projects = Project.all
  end

  def get_clients
    @clients = Client.all
  end

  def add_files
    permit_files
    save_files(@project, params[:project][:files])
  end

  def add_projectmanager_role
    @role = Role.new(projectmanager_role_params)
    @role.save
  end

  def update_projectmanager_role
    @role = @project.roles.where(:role => "projectmanager").take
    @role.update(projectmanager_role_params)
  end

  def projectmanager_role_params
    @employee = Employee.find(params[:project][:employee_id])
    role_params = { "project_id": @project.id, "employee_id": @employee.id, "role": "projectmanager" }
  end

  def destroy_existing_developers
    @project.roles.each do |role|
      if role.role == "developer" #is_developer? pe role model (de ce ar fi mai util asa tho?)
        role.destroy
      end
    end
  end

  def destroy_existing_testers
    @project.roles.each do |role|
      if role.role == "tester"
        role.destroy
      end
    end
  end

  def developer_role_params(developer_id)
    role_params = { "project_id": @project.id, "employee_id": developer_id, "role": "developer" }
  end

  def tester_role_params(developer_id)
    role_params = { "project_id": @project.id, "employee_id": developer_id, "role": "tester" }
  end

end

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true, class: 'form-horizontal' do |form| %>

  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:
    </h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="container-fluid">
    <div class="form-group required">
      <%= form.label :title, class: 'control-label col-sm-1'%>
      <div class="col-sm-4">
        <%= form.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :attachments, class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <% @project.attachments.each do |attachment| %>
          <%= link_to project_delete_attachment_path(@project, attachment), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete attachment' do %>
            <i class="glyphicon glyphicon-remove"></i>
          <% end %>
          <%= link_to attachment.filename, attachment.file.url, target: :_blank %><br>
        <% end %>
        <%= form.file_field :files, class: 'form-control-file', multiple: true  %>
      </div>
    </div>

    <div class="form-group required">
      <%= form.label 'Project manager', class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <% if @projectmanager.nil? %> <!-- new action -->
          <%= form.select :employee_id, options_from_collection_for_select(@employees, "id", "full_name", 1) %>
        <% else %> <!-- edit action -->
          <%= form.select :employee_id, options_from_collection_for_select(@employees, "id", "full_name", @projectmanager.id) %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label 'Clients', class: 'control-label col-sm-1' %>
      <div class="col-sm-4">
        <%= form.collection_check_boxes :client_ids, @clients, :id, :full_name, { include_hidden: false } do |client| %>
          <div class="collection-check-box">
            <%= client.check_box %>
            <%= client.label %>
          </div>
        <% end %>
      </div>
    </div>

    <br>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-1">
        <%= form.submit "Save" %>
      </div>
      <%= link_to '<button type="button">Cancel</button>'.html_safe, projects_path, style: 'color: black;' %>
    </div>

    <br>
    <p><span style="color:red">* </span>fields are mandatory</p>

  </div>
<% end %>

app/views/projects/_left_sidebar.html.erb
<div class="sidenav">
  <% if current_user.can_see_projects? %>
    <% @projects.each do |project| %>
      <%= link_to project.title, project_path(project) %>
    <% end %>
  <% end %>

  <% if current_user.can_modify_project? %>
    <div class="footer">
      <%= link_to 'Add new project', new_project_path %>
    </div>
  <% end %>

  <% if current_user.can_see_project_roles? %>
    <h3>Project manager</h3>
    <% @projects_projectmanager_role.each do |project| %>
      <%= link_to project.title, project_dashboard_index_path(project.id) %>
    <% end %>

    <h3>Developer</h3>
    <% @projects_developer_role.each do |project| %>
      <%= link_to project.title, project_dashboard_index_path(project.id) %>
    <% end %>

    <h3>Tester</h3>
    <% @projects_tester_role.each do |project| %>
      <%= link_to project.title, project_dashboard_index_path(project.id)%>
    <% end %>
  <% end %>
</div>

app/views/projects/developers.html.erb
<%= render 'left_sidebar' %>
<%= render 'dashboard/tabs' %>

<%= form_with :url => { :controller => "projects", :action => "manage_developers" } do |form| %>
  <h2>Manage developers</h2>
  <h4>Check to add and uncheck to delete developers from the project</h4>
  <%= form.collection_check_boxes :developer_ids, @available_employees, :id, :full_name, { include_hidden: false } do |f| %>
    <div class="collection-check-box">
      <% if f.object.is_developer?(@project) %>
        <%= f.check_box(checked: true) %>
        <% else %>
        <%= f.check_box %>
      <% end %>
      <%= f.label %>
    </div>
   <% end %><br>
   <%= form.submit "Save" %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'left_sidebar' %>

<div class="main">
  <h1>Edit project</h1>
  <%= render 'form' %>
</div>

app/views/projects/new.html.erb
<%= render 'left_sidebar' %>

<div class="main">
  <h1>Fill in form to add a new project</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<%= render 'left_sidebar' %>
<%= render 'dashboard/tabs' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-lg-6">

      <table class="table table-user-information">
        <tbody>
          <tr>
            <td><b>Title:<b></td>
            <td><%= @project.title %></td>
          </tr>
          <tr>
            <td><b>Description:</b></td>
            <td><%= @project.description %></td>
          </tr>
          <tr>
            <td><b>Clients:</b></td>
            <td>
              <% @project.clients.each do |client| %>
                  <%= client.full_name %><br>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><b>Project manager:</b></td>
            <td>
              <%= @projectmanager.full_name %>
            </td>
          </tr>
          <% if current_user.can_see_project_team? %>
            <tr>
              <td><b>Developers:</b><br>
                <% if current_user.can_modify_project? || current_user.is_projectmanager?(@project) %>
                  <%= link_to project_developers_path(@project), class: 'btn btn-success', title: 'Manage developers' do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% @developers.each do |developer| %>
                  <%= developer.full_name %><br>
                <% end %>
              </td>
            </tr>
            <tr>
              <td><b>Testers:</b><br>
                <% if current_user.can_modify_project? || current_user.is_projectmanager?(@project) %>
                  <%= link_to project_testers_path(@project), class: 'btn btn-success', title: 'Manage testers' do %>
                    <i class="glyphicon glyphicon-pencil"></i>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% @testers.each do |tester| %>
                  <%= tester.full_name %><br>
                <% end %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td><b>Attachments:</b></td>
            <td>
              <% @project.attachments.each do |attachment| %>
                <% if attachment.file.is_other? %>
                  <%= link_to attachment.file.get_original_filename, download_file_path(@project, attachment.file), target: :_blank %><br>
                <% else %>
                  <%= link_to attachment.filename, attachment.file.url, target: :_blank %><br>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

        <% if current_user.can_modify_project? %>
          <%= link_to edit_project_path(@project), class: 'btn btn-warning', title: 'Edit project' do %>
            <i class="glyphicon glyphicon-edit"></i>
          <% end %>
          <%= link_to project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', title: 'Delete project' do %>
            <i class="glyphicon glyphicon-remove"></i>
          <% end %>
        <% end %>

    </div>

    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
      <%= pie_chart @project.get_employee_hash_for_piechart, donut: true, width: "700px" %>
    </div>

  </div>
</div>

app/views/projects/testers.html.erb
<%= render 'left_sidebar' %>
<%= render 'dashboard/tabs' %>

<%= form_with :url => { :controller => "projects", :action => "manage_testers" } do |form| %>
  <h2>Manage testers</h2>
  <h4>Check to add and uncheck to delete testers from the project</h4>
  <%= form.collection_check_boxes :tester_ids, @available_employees, :id, :full_name, { include_hidden: false } do |f| %>
    <div class="collection-check-box">
      <% if f.object.is_tester?(@project) %>
        <%= f.check_box(checked: true) %>
        <% else %>
        <%= f.check_box %>
      <% end %>
      <%= f.label %>
    </div>
   <% end %><br>
   <%= form.submit "Save" %>
<% end %>