config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :admin, only: [:index]
  resources :clients
  resources :projects do
    resources :tickets
    resources :dashboard, only: [:index]
    resources :chat, only: [:index, :create]
    resources :reports, only: [:index, :show, :new, :create, :destroy]
  end
  resources :employees

  resources :tickets, only: [:show] do
    resources :comments
  end

  get 'projects/:id/developers' => 'projects#developers', as: :project_developers
  get 'projects/:id/testers' => 'projects#testers', as: :project_testers
  post '/projects/:id/developers' => 'projects#manage_developers'
  post '/projects/:id/testers' => 'projects#manage_testers'

  #not sure this is the right way to do it
  #voiam doar ca o actiune din controller sa se execute in momentul in care se apasa pe un buton
  put '/projects/:project_id/dashboard/change_status/:ticket_id' => 'dashboard#change_status', as: :change_status

  #for downloading file in a ticket
  get '/projects/:id/dashboard/:attachment' => 'dashboard#download', :constraints => {:attachment => /.*/ }, as: :download_file

  #for subtasks
  get '/projects/:project_id/tickets/new/(:owner)' => 'tickets#new', as: :new_project_subticket

  #deleting attachments
  delete 'projects/:id/attachment/:attachment_id' => 'projects#delete_attachment', as: :project_delete_attachment
  delete 'tickets/:id/attachment/:attachment_id' => 'tickets#delete_attachment', as: :ticket_delete_attachment
  delete 'tickets/:ticket_id/comments/:id/attachment/:attachment_id' => 'comments#delete_attachment', as: :comment_delete_attachment

  #tickets details
  get '/projects/:project_id/tickets/:id/time_tracking' => 'tickets#time_tracking', as: :ticket_time_tracking
  get '/projects/:project_id/tickets/:id/attachments' => 'tickets#attachments', as: :ticket_attachments

  #cum pot sa accesez o actiune din controller fara sa creez o intreaga ruta pt asta?
  #am incercat cu <%= link_to "", controller: "comments", action: "decrease_step" do %> dar nu a mers
  put 'tickets/:ticket_id/decrease_step' => 'comments#decrease_step', as: :decrease_step
  put 'tickets/:ticket_id/increase_step' => 'comments#increase_step', as: :increase_step

  #for reports
  post '/projects/:project_id/reports/tickets_priority' => 'reports#tickets_priority'
  post '/projects/:project_id/reports/refill_employees_dropdown' => 'reports#refill_employees_dropdown'

  #for realtime chat
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  serialize :settings, JSON

  belongs_to :user
  belongs_to :project

  #validates_presence_of :title, :if => :save_as_template?
  def from_ids_to_full_names
    full_names = []

    unless settings['employees'].nil?
      settings['employees'].each do |employee_id|
        full_names.push(Employee.find(employee_id).full_name)
      end
    end

    full_names
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :setup_left_sidebar, only: [:index, :show, :new, :create]
  before_action :find_report_by_id, only: [:show, :destroy]
  before_action :get_current_project, only: [:index, :show, :new, :create]
  before_action :get_entities_for_dropdowns, only: [:show, :new]

  def index
    @reports = current_user.get_reports(@project.id).paginate(:page => params[:page], :per_page => 15)
  end

  def show
    set_up_conditions
    tickets_priority_piechart
    tickets_status_piechart
    nr_tickets_per_employee_columnchart
    ticket_start_and_end_date_linechart
    tickets_for_calendar_and_timeline
  end

  def new
  end

  def create
    report = Report.new(title: report_params['title'], user_id: current_user.id, project_id: @project.id, show_to_client: report_params['show_to_client'], save_as_template: report_params['save_as_template'],
                        settings: report_params.except('title', 'show_to_client', 'save_as_template'))
    report.settings['employees'].map!{ |e| Employee.find_by(first_name: e.split()[0], last_name: e.split()[1]).id } if report.settings['employees']
    # ^ because in employees dropdown I only have employees's full names, not employees entities or ids
    report.settings.merge!(projects: [@project.id.to_s]) if current_user.is_projectmanager?(@project)
    # ^ when project manager creates a report, settings['projects'] must include report's project

    if report.save
      redirect_to project_report_path(@project, report)
    else
      render 'new'
    end
  end

  def destroy
    @report.destroy
    redirect_to project_reports_path
  end

  def refill_employees_dropdown
    @employees = []
    Role.where(project_id: params[:selected_projects]).each do |role|
      @employees.push(Employee.find(role.employee_id))
    end

    render json: { employees: @employees.map{|e| e.full_name} }
  end

  private

  def report_params
    params.require(:report).permit(:from_date, :to_date, :title, :show_to_client, :save_as_template, :projects => [], :employees => [], :tickets => [], :statuses => [])
    # ':array => []' -> syntax has to be like this when working with arrays (and always at the end of the method !)
  end

  def find_report_by_id
    @report = Report.find(params[:id])
  end

  def get_current_project
    @project = Project.find(params[:project_id])
  end

  def get_entities_for_dropdowns
    if current_user.is_projectmanager?(@project)
      @employees = @project.employees - [current_user]
    else
      @projects = Project.all
      @employees = Employee.all
    end
  end

  def set_up_conditions
    @conditions = { project_id: @report.settings['projects'], employee_id: @report.settings['employees'], type: @report.settings['tickets'], status: @report.settings['statuses'] }
    @conditions[:created_at] = (@report.settings['from_date']..@report.settings['to_date']) unless (@report.settings['from_date'].empty? || @report.settings['to_date'].empty?)
    @conditions.delete_if { |k, v| v.blank? }
  end

  def tickets_priority_piechart
    @tickets_by_priority = Ticket.where(@conditions).group_by(&:priority)
    @tickets_by_priority['low'] = [] if @tickets_by_priority['low'].nil?
    @tickets_by_priority['medium'] = [] if @tickets_by_priority['medium'].nil?
    @tickets_by_priority['high'] = [] if @tickets_by_priority['high'].nil?
  end

  def tickets_status_piechart
    @tickets_by_status = Ticket.where(@conditions).group_by(&:status)
    @tickets_by_status['To do'] = [] if @tickets_by_status['To do'].nil?
    @tickets_by_status['In progress'] = [] if @tickets_by_status['In progress'].nil?
    @tickets_by_status['Complete'] = [] if @tickets_by_status['Complete'].nil?
    @tickets_by_status['Done'] = [] if @tickets_by_status['Done'].nil?
  end

  def nr_tickets_per_employee_columnchart
    @employees_for_columnchart = []

    if !@report.settings['employees'].nil?          #used ' if ! ' instead of 'unless' because 'unless' doesn't support elsif
      Employee.get_selected_employees_for_columnchart(@employees_for_columnchart, @report.settings['employees'])
    elsif !@report.settings['projects'].nil?        #when no employee is selected but some projects are
      Project.get_employees_from_selected_projects_for_columnchart(@employees_for_columnchart, @report.settings['projects'])
    elsif !@report.settings['tickets'].nil? || !@report.settings['statuses'].nil?       #when only tickets or statuses is selected
      Ticket.get_employees_from_selected_tickets_for_columnchart(@employees_for_columnchart, @conditions)
    else
      @employees_for_columnchart = Employee.all     #when nothing is selected
    end
  end

  def ticket_start_and_end_date_linechart
    @tickets_created_at_by_week = Ticket.where(@conditions).group_by{ |t| t.created_at.end_of_week.strftime("%Y-%m-%d") }
    @tickets_ended_at_by_week = Ticket.where(@conditions).reject{ |t| t.ended_at.nil? }.group_by{ |t| t.ended_at.end_of_week.strftime("%Y-%m-%d") }

    @tickets_by_week = {}.merge(@tickets_created_at_by_week).merge(@tickets_ended_at_by_week) #to have all end of weeks from both created_at and ended_at tickets
    @tickets_by_week.keys.sort.each do |week|
      @tickets_created_at_by_week[week] ? @tickets_by_week[week][0] = @tickets_created_at_by_week[week].length : @tickets_by_week[week][0] = 0
      @tickets_ended_at_by_week[week] ? @tickets_by_week[week][1] = @tickets_ended_at_by_week[week].length : @tickets_by_week[week][1] = 0
    end
    #@tickets_by_week has: key -> end of week date, value -> [nr_of_created_tickets, nr_of_ended_tickets]
  end

  def tickets_for_calendar_and_timeline
    @tickets = Ticket.where(@conditions)
  end
end

app/views/reports/_reports_settings.html.erb
<%= form_with model: [@project, Report.new], class: 'reports-form' do |f| %>
  <table>
    <tr>
      <td>
        <%= link_to "All reports", project_reports_path(@project), class: "btn", id: 'show-all-reports' %>
      </td>
    </tr>

    <tr>
      <td>
        <% if current_user.type == "Admin" %>
          <div id="projects-dropdown" class="display-inline">
            <%= f.select :projects, options_from_collection_for_select(@projects, "id", "title"), { include_hidden: false }, { multiple: true } %>
          </div>
        <% end %>
      </td>

      <td>
        <div id="employees-dropdown" class="display-inline">
          <%= f.select :employees, options_from_collection_for_select(@employees, "full_name", "full_name"), { include_hidden: false }, { multiple: true } %>
        </div>
      </td>

      <td>
        <div id="tickets-dropdown" class="display-inline">
          <%= f.select :tickets, options_for_select(["Task", "Bug"]), { include_hidden: false }, { multiple: true } %>
        </div>
      </td>

      <td>
        <div id="tickets-status-dropdown" class="display-inline">
          <%= f.select :statuses, options_for_select(["To do", "In progress", "Complete", "Done"]), { include_hidden: false }, { multiple: true } %>
        </div>
      </td>

      <td>
        <div class='report-datetimepicker-wrapper input-group display-inline'>
          <div class="input-group-addon">
            <span class="input-group-text">From</span>
          </div>
          <%= f.text_field :from_date, autocomplete: 'off', class: 'form-control', id: 'report-from-datetimepicker' %>
          <div class="input-group-addon">
            <span class="input-group-text">To</span>
          </div>
          <%= f.text_field :to_date, autocomplete: 'off', class: 'form-control', id: 'report-to-datetimepicker' %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </td>

      <td>
        <div id="report-title" class="display-inline">
          <%= f.text_field :title, placeholder: 'Title', autocomplete: 'off', style: 'width: 150px; height: 40px' %>
        </div>
      </td>

      <td>
        <div id="report-send-to-client-checkbox" class="checkbox-inline">
        <%= f.label :show_to_client do %>
          <%= f.check_box :show_to_client %>
          Show to client
          <% end %>
        </div>
      </td>

      <td>
        <div id="report-save-as-template-checkbox" class="checkbox-inline" >
        <%= f.label :save_as_template do %>
          <%= f.check_box :save_as_template %>
          Save as template
          <% end %>
        </div>
      </td>

      <td>
        <div class="display-inline report-generation-button">
          <%= f.submit 'Generate Report', class: 'btn btn-primary' %>
        </div>
      </td>
    </tr>
  </table>

<% end %>

app/views/reports/index.html.erb
<%= render 'projects/left_sidebar' %>
<%= render 'dashboard/tabs' %>

<div class="container-fluid">
  <table class="reports-table table table-borderless">
  <thead>
    <tr>
      <th class="col-xs-1 col-sm-1 col-md-1 col-lg-1"></th>
      <th class="col-xs-1 col-sm-1 col-md-1 col-lg-1">Crt. No.</th>
      <th class="col-xs-5 col-sm-5 col-md-5 col-lg-5">Title</th>
      <th class="col-xs-3 col-sm-3 col-md-3 col-lg-3">Created at</th>
      <th class="col-xs-2 col-sm-2 col-md-2 col-lg-2">Shown to client</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>
          <%= link_to project_report_path(@project, report), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete report' do %>
            <i class="glyphicon glyphicon-remove pull-right"></i>
          <% end %>
        </td>
        <td><%= link_to report.id, project_report_path(@project, report), data: { turbolinks: false } %></td>
        <td><%= link_to report.title, project_report_path(@project, report), data: { turbolinks: false } unless report.title.nil? %></td>
        <td><%= report.format_date(report.created_at) unless report.created_at.nil? %></td>
        <td><% if report.show_to_client %><i class="glyphicon glyphicon-ok"></i> <% end %> </td>
      </tr>
    <% end %>
  </tbody>
  </table>

  <hr>
  <div class="display-inline">
    <%= link_to 'New', new_project_report_path(@project), class: 'chart-title-design' %>
  </div> |
  <div class="display-inline">
    <span class="chart-title-design">Templates:</span>
    <% @reports.select { |report| report.save_as_template }.each do |report| %>
      <%= link_to report.title, new_project_report_path(@project), onclick: "template_setup(this);",
          'data-projects': report.settings['projects'], 'data-employees': report.from_ids_to_full_names, 'data-tickets': report.settings['tickets'], 'data-statuses': report.settings['statuses'],
          'data-from-date': report.settings['from_date'], 'data-to-date': report.settings['to_date'], 'data-title': report.title, 'data-client': report.show_to_client %>
    <% end %>
  </div>

  <div style="text-align: center;">
    <%= will_paginate @reports %>
  <div>
</div>

app/views/reports/new.html.erb
<%= render 'projects/left_sidebar' %>
<%= render 'dashboard/tabs' %>

<div class="container-fluid">

  <%= render 'reports_settings' %>

</div>

app/views/reports/show.html.erb
<%= render 'projects/left_sidebar' %>
<%= render 'dashboard/tabs' %>

<div class="container-fluid">
  <%= render 'reports_settings' %>

  <%= render 'charts' %>
</div>